#!/bin/sh

rsync -rav --delete -e 'ssh -i ./.scaleway' \
	--exclude '.*' \
	--exclude node_modules \
	. 'root@vbb-monitor.jannisr.de:~/vbb-monitor/'

ssh -i ./.scaleway 'root@vbb-monitor.jannisr.de' "\
cd ~/vbb-monitor
npm i
export NODE_ENV=production
forever stop vbb-monitor
rm data.ndjson.gzip
forever start -a --uid vbb-monitor build.js"
